Repository codingtest-break/algorithm-study, pull requests merged in 2022-06, with the labels that each got.

#1 DOCUMENT-1 스터디 계획 및 방법과 Git 가이드 1차 작성
  README.md
  doc/asset/image/git/no-remote.001.jpeg
  doc/asset/image/git/only-local.001.jpeg
  doc/asset/image/git/remote.001.jpeg
  doc/git/git-flow.md
  doc/git/git.md
  doc/pull_request_template.md
  pull_request_template.md
Labels: documentation

#3 IO-malleus35-1 Java 기본 입출력 문제 해결
  code/boj/io/Baekjoon_io_malleus35_b2_10953.java
  code/boj/io/Baekjoon_io_malleus35_b3_11021.java
  code/boj/io/Baekjoon_io_malleus35_b3_11022.java
  code/boj/io/Baekjoon_io_malleus35_b5_1000.java
  code/boj/io/Baekjoon_io_malleus35_b5_10950.java
  code/boj/io/Baekjoon_io_malleus35_b5_10951.java
  code/boj/io/Baekjoon_io_malleus35_b5_10952.java
  code/boj/io/Baekjoon_io_malleus35_b5_15740.java
  code/boj/io/Baekjoon_io_malleus35_b5_2558.java
Labels: Basic IO

#5 BackTracking_N&M
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s2_15663.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s2_15664.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s2_15665.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s2_15666.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15649.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15650.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15651.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15652.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15654.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15655.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15656.java
  code/boj/backtracking/Baekjoon_backtracking_codingmate_s3_15657.java
Labels: Algorithm, BackTracking
